### ISSUE TITLE
Problem when resizing

### ISSUE THREAD

**Issue by alexadam** [alexadam/bridges#11]
when resizing the browser, the stl viewer dimensions change to full screen. This is a mistake and it should keep the same aspect ratio/resolution (screen.width * 0.8). You can change this in STLViewer -> applyResize() (or by removing the resize code and doing it with CSS)

initial:

![ss2](https://cloud.githubusercontent.com/assets/1687725/19476907/4dd08efa-9544-11e6-8371-2b12439708dd.png)

vs resized:

![ss1](https://cloud.githubusercontent.com/assets/1687725/19476909/51a39324-9544-11e6-8381-8c8c94fe6855.png)

**Comment by kaesve** [comment]
I have implemented the suggested fix. Let me know if there are contributor guidelines that I you want me to follow :)
